CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    name VARCHAR(255) NOT NULL,
    purpose TEXT,
    dose VARCHAR(255),
    frequency VARCHAR(255),
    water_intake_note TEXT,
    explanation TEXT,
    source VARCHAR(40) NOT NULL,
    last_taken_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE blood_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    summary TEXT,
    flagged_json TEXT,
    recommendations_json TEXT,
    source VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE water_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    ph DOUBLE PRECISION,
    tds DOUBLE PRECISION,
    chlorine DOUBLE PRECISION,
    verdict VARCHAR(40) NOT NULL,
    triggered_by VARCHAR(255),
    explanation TEXT,
    source VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    source VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

INSERT INTO users (display_name, created_at) VALUES ('Default user', CURRENT_TIMESTAMP);
